import tkinter as tk
from tkinter import ttk
from PIL import ImageTk, Image
import sqlite3

paint_list = [
    (0, 'Abaddon Black', 'Citadel', 'Paint'),
    (0, 'Administratum Grey', 'Citadel', 'Paint'),
    (0, 'Ahriman Blue', 'Citadel', 'Paint'),
    (0, 'Alaitoc Blue', 'Citadel', 'Paint'),
    (0, 'Altdorf Guard Blue', 'Citadel', 'Paint'),
    (0, 'Auric Armour Gold', 'Citadel', 'Metallic'),
    (0, 'Averland Sunset', 'Citadel', 'Paint'),
    (0, 'Baharroth Blue', 'Citadel', 'Paint'),
    (0, 'Balor Brown', 'Citadel', 'Paint'),
    (0, 'Balthasar Gold', 'Citadel', 'Metallic'),
    (0, 'Baneblade Brown', 'Citadel', 'Paint'),
    (0, 'Barak-Nar Burgundy', 'Citadel', 'Paint'),
    (0, 'Bestigor Flesh', 'Citadel', 'Paint'),
    (0, 'Bloodreaver Flesh', 'Citadel', 'Paint'),
    (0, 'Brass Scorpion', 'Citadel', 'Metallic'),
    (0, 'Cadian Fleshtone', 'Citadel', 'Paint'),
    (0, 'Calgar Blue', 'Citadel', 'Paint'),
    (0, 'Caledor Sky', 'Citadel', 'Paint'),
    (0, 'Caliban Green', 'Citadel', 'Paint'),
    (0, 'Canoptek Alloy', 'Citadel', 'Metallic'),
    (0, 'Castellax Bronze', 'Citadel', 'Metallic'),
    (0, 'Catachan Flesh', 'Citadel', 'Paint'),
    (0, 'Celestra Grey', 'Citadel', 'Paint'),
    (0, 'Ceramite White', 'Citadel', 'Paint'),
    (0, 'Corvus Black', 'Citadel', 'Paint'),
    (0, 'CORAX WHITE', 'Citadel', 'Paint'),
    (0, 'Daemonette Hide', 'Citadel', 'Paint'),
    (0, 'Dark Reaper', 'Citadel', 'Paint'),
    (0, 'Dawnstone', 'Citadel', 'Paint'),
    (0, 'Death Guard Green', 'Citadel', 'Paint'),
    (0, 'Death Korps Drab', 'Citadel', 'Paint'),
    (0, 'Deathclaw Brown', 'Citadel', 'Paint'),
    (0, 'Deathworld Forest', 'Citadel', 'Paint'),
    (0, 'Deepkin Flesh', 'Citadel', 'Paint'),
    (0, 'Doombull Brown', 'Citadel', 'Paint'),
    (0, 'Dorn Yellow', 'Citadel', 'Paint'),
    (0, 'Elysian Green', 'Citadel', 'Paint'),
    (0, "Emperor's Children", 'Citadel', 'Paint'),
    (0, 'Eshin Grey', 'Citadel', 'Paint'),
    (0, 'Etherium Blue', 'Citadel', 'Paint'),
    (0, 'Evil Sunz Scarlet', 'Citadel', 'Paint'),
    (0, 'Fenrisian Grey', 'Citadel', 'Paint'),
    (0, 'Fire Dragon Bright', 'Citadel', 'Paint'),
    (0, 'Flash Gitz Yellow', 'Citadel', 'Paint'),
    (0, 'Flayed One Flesh', 'Citadel', 'Paint'),
    (0, 'Fulgrim Pink', 'Citadel', 'Paint'),
    (0, 'Fulgurite Copper', 'Citadel', 'Metallic'),
    (0, 'Gal Vorbak Red', 'Citadel', 'Paint'),
    (0, "Gehenna's Gold", 'Citadel', 'Metallic'),
    (0, 'Genestealer Purple', 'Citadel', 'Paint'),
    (0, 'Gorthor Brown', 'Citadel', 'Paint'),
    (0, 'Grey Seer', 'Citadel', 'Paint'),
    (0, 'Hashut Copper', 'Citadel', 'Metallic'),
    (0, 'Hobgrot Hide', 'Citadel', 'Paint'),
    (0, 'Hoeth Blue', 'Citadel', 'Paint'),
    (0, 'Incubi Darkness', 'Citadel', 'Paint'),
    (0, 'Ionrach Skin', 'Citadel', 'Paint'),
    (0, 'Ironbreaker', 'Citadel', 'Metallic'),
    (0, 'Iron Hands Steel', 'Citadel', 'Paint'),
    (0, 'Iron Warriors', 'Citadel', 'Paint'),
    (0, 'Jokaero Orange', 'Citadel', 'Paint'),
    (0, 'Kakophoni Purple', 'Citadel', 'Paint'),
    (0, 'Kantor Blue', 'Citadel', 'Paint'),
    (0, 'Karak Stone', 'Citadel', 'Paint'),
    (0, 'Khorne Red', 'Citadel', 'Paint'),
    (0, 'Kislev Flesh', 'Citadel', 'Paint'),
    (0, 'Knight-Questor Flesh', 'Citadel', 'Paint'),
    (0, 'Krieg Khaki', 'Citadel', 'Paint'),
    (0, 'Leadbelcher', 'Citadel', 'Metallic'),
    (0, 'Liberator Gold', 'Citadel', 'Metallic'),
    (0, 'Longbeard Grey', 'Citadel', 'Paint'),
    (0, 'Loren Forest', 'Citadel', 'Paint'),
    (0, 'Lothern Blue', 'Citadel', 'Paint'),
    (0, 'Lugganath Orange', 'Citadel', 'Paint'),
    (0, 'Lupercal Green', 'Citadel', 'Paint'),
    (0, 'Macragge Blue', 'Citadel', 'Paint'),
    (0, 'Mechanicus Standard Grey', 'Citadel', 'Paint'),
    (0, 'Mephiston Red', 'Citadel', 'Paint'),
    (0, 'Moot Green', 'Citadel', 'Paint'),
    (0, 'Morghast Bone', 'Citadel', 'Paint'),
    (0, 'Mournfang Brown', 'Citadel', 'Paint'),
    (0, 'Naggaroth Night', 'Citadel', 'Paint'),
    (0, 'Nurgling Green', 'Citadel', 'Paint'),
    (0, 'Ogryn Camo', 'Citadel', 'Paint'),
    (0, 'Orruk Flesh', 'Citadel', 'Paint'),
    (0, 'Pallid Wych Flesh', 'Citadel', 'Paint'),
    (0, 'Phalanx Yellow', 'Citadel', 'Paint'),
    (0, 'Phoenician Purple', 'Citadel', 'Paint'),
    (0, 'Rakarth Flesh', 'Citadel', 'Paint'),
    (0, 'Ratskin Flesh', 'Citadel', 'Paint'),
    (0, 'Retributor Armour', 'Citadel', 'Metallic'),
    (0, 'Rhinox Hide', 'Citadel', 'Paint'),
    (0, 'Runefang Steel', 'Citadel', 'Metallic'),
    (0, 'Runelord Brass', 'Citadel', 'Metallic'),
    (0, 'Russ Grey', 'Citadel', 'Paint'),
    (0, 'Screamer Pink', 'Citadel', 'Paint'),
    (0, 'Screaming Bell', 'Citadel', 'Metallic'),
    (0, 'Screaming Skull', 'Citadel', 'Paint'),
    (0, 'Skarsnik Green', 'Citadel', 'Paint'),
    (0, 'Skavenblight Dinge', 'Citadel', 'Paint'),
    (0, 'Skrag Brown', 'Citadel', 'Paint'),
    (0, 'Skullcrusher Brass', 'Citadel', 'Metallic'),
    (0, 'Slaanesh Grey', 'Citadel', 'Paint'),
    (0, 'Sotek Green', 'Citadel', 'Paint'),
    (0, 'Squig Orange', 'Citadel', 'Paint'),
    (0, 'Steel Legion Drab', 'Citadel', 'Paint'),
    (0, 'Tallarn Sand', 'Citadel', 'Paint'),
    (0, 'Tau Light Ochre', 'Citadel', 'Paint'),
    (0, 'Teclis Blue', 'Citadel', 'Paint'),
    (0, 'Temple Guard Blue', 'Citadel', 'Paint'),
    (0, 'The Fang', 'Citadel', 'Paint'),
    (0, 'Thunderhawk Blue', 'Citadel', 'Paint'),
    (0, 'Troll Slayer Orange', 'Citadel', 'Paint'),
    (0, 'Tuskgor Fur', 'Citadel', 'Paint'),
    (0, 'Ulthuan Grey', 'Citadel', 'Paint'),
    (0, 'Ungor Flesh', 'Citadel', 'Paint'),
    (0, 'Ushabti Bone', 'Citadel', 'Paint'),
    (0, 'Valdor Gold', 'Citadel', 'Metallic'),
    (0, 'Warboss Green', 'Citadel', 'Paint'),
    (0, 'Warpfiend Grey', 'Citadel', 'Paint'),
    (0, 'Warplock Bronze', 'Citadel', 'Metallic'),
    (0, 'Warpstone Glow', 'Citadel', 'Paint'),
    (0, 'Wazdakka Red', 'Citadel', 'Paint'),
    (0, 'White Scar', 'Citadel', 'Paint'),
    (0, 'Wild Rider Red', 'Citadel', 'Paint'),
    (0, 'Wraithbone', 'Citadel', 'Paint'),
    (0, 'Xereus Purple', 'Citadel', 'Paint'),
    (0, 'Yriel Yellow', 'Citadel', 'Paint'),
    (0, 'Zamesi Desert', 'Citadel', 'Paint'),
    (0, 'Zandri Dust', 'Citadel', 'Paint'),
    (0, 'Agrax Earthshade', 'Citadel', 'Wash'),
    (0, 'Athonian Camoshade', 'Citadel', 'Wash'),
    (0, 'Biel-Tan Green', 'Citadel', 'Wash'),
    (0, 'Carroburg Crimson', 'Citadel', 'Wash'),
    (0, 'Casandora Yellow', 'Citadel', 'Wash'),
    (0, 'Coelia Greenshade', 'Citadel', 'Wash'),
    (0, 'Drakenhof Nightshade', 'Citadel', 'Wash'),
    (0, 'Druchii Violet', 'Citadel', 'Wash'),
    (0, 'Fuegan Orange', 'Citadel', 'Wash'),
    (0, 'Nuln Oil', 'Citadel', 'Wash'),
    (0, 'Reikland Fleshshade', 'Citadel', 'Wash'),
    (0, 'Seraphim Sepia', 'Citadel', 'Wash'),
    (0, 'Aeldari Emerald', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Aethermatic Blue', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Akhelian Green', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Aggaros Dunes', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Apothecary White', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Baal Red', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Bad Moon Yellow', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Basilicanum Grey', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Black Legion', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Black Templar', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Blood Angels Red', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Briar Queen Chill', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Cygor Brown', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Dark Angels Green', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Darkoath Flesh', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Dreadful Visage', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Flesh Tearers Red', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Frostheart', 'Citadel', 'Contrast/Speed Paint'),
    (0, "Garaghak's Sewer", 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Gore-Grunta Fur', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Guilliman Flesh', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Gryph-Charger Grey', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Gryph-Hound Orange', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Hexwraith Flame', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Imperial Fist', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Ironjawz Yellow', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Iyanden Yellow', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Karandras Green', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Kroxigor Scales', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Leviadon Blue', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Leviathan Purple', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Magmadroth Flame', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Magos Purple', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Mantis Warriors Green', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Militarum Green', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Nazdreg Yellow', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Nighthaunt Gloom', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Night Lords Blue', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Nocturne Green', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Ork Flesh', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Plaguebearer Flesh', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Pylar Glacier', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Ratling Grime', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Screaming Skull', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Shyish Purple', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Sigvald Burgundy', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Skeleton Horde', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Snakebite Leather', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Sons of Horus Green', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Space Wolves Grey', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Striking Scorpion Green', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Terradon Turquoise', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Ultramarines Blue', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Volupus Pink', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Waaagh! Flesh', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Warp Lightning', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Wyldwood', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Xereus Purple', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Yriel Yellow', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Zamesi Desert', 'Citadel', 'Contrast/Speed Paint'),
    (0, 'Agrellan Badland', 'Citadel', 'Texture'),
    (0, 'Agrellan Earth', 'Citadel', 'Texture'),
    (0, 'Armageddon Dust', 'Citadel', 'Texture'),
    (0, 'Armageddon Dunes', 'Citadel', 'Texture'),
    (0, 'Astrogranite', 'Citadel', 'Texture'),
    (0, 'Astrogranite Debris', 'Citadel', 'Texture'),
    (0, 'Blackfire Earth', 'Citadel', 'Texture'),
    (0, 'Lustrian Undergrowth', 'Citadel', 'Texture'),
    (0, 'Martian Ironcrust', 'Citadel', 'Texture'),
    (0, 'Martian Ironearth', 'Citadel', 'Texture'),
    (0, 'Mourn Mountain Snow', 'Citadel', 'Texture'),
    (0, 'Stirland Battlemire', 'Citadel', 'Texture'),
    (0, 'Stirland Mud', 'Citadel', 'Texture'),
    (0, 'Valhallan Blizzard', 'Citadel', 'Texture'),
    (0, 'Bloodletter', 'Citadel', 'Ink'),
    (0, 'Guilliman Blue', 'Citadel', 'Ink'),
    (0, 'Lamenters Yellow', 'Citadel', 'Ink'),
    (0, 'Waywatcher Green', 'Citadel', 'Ink'),
    (0, 'Imperial Primer', 'Citadel', 'Primer'),
    (0, "'Ardcoat", 'Citadel', 'Technical'),
    (0, 'Agrellan Earth', 'Citadel', 'Technical'),
    (0, 'Blood for the Blood God', 'Citadel', 'Technical'),
    (0, 'Lahmian Medium', 'Citadel', 'Technical'),
    (0, 'Liquid Green Stuff', 'Citadel', 'Technical'),
    (0, 'Martian Ironearth', 'Citadel', 'Technical'),
    (0, 'Nihilakh Oxide', 'Citadel', 'Technical'),
    (0, "Nurgle's Rot", 'Citadel', 'Technical'),
    (0, 'Soulstone Blue', 'Citadel', 'Technical'),
    (0, 'Spiritstone Red', 'Citadel', 'Technical'),
    (0, 'Typhus Corrosion', 'Citadel', 'Technical'),
    (0, 'Waystone Green', 'Citadel', 'Technical'),
    (0, 'Chaos Black', 'Citadel', 'Primer'),
    (0, 'Corax White', 'Citadel', 'Primer'),
    (0, 'Grey Seer', 'Citadel', 'Primer'),
    (0, 'Mechanicus Standard Grey', 'Citadel', 'Primer'),
    (0, 'Wraithbone', 'Citadel', 'Primer'),
    (0, 'Leadbelcher', 'Citadel', 'Primer'),
    (0, 'Retributor Armour', 'Citadel', 'Primer'),
    (0, 'Zandri Dust', 'Citadel', 'Primer'),
    (0, 'Mephiston Red', 'Citadel', 'Primer'),
    (0, 'Death Guard Green', 'Citadel', 'Primer'),
    (0, 'Macragge Blue', 'Citadel', 'Primer'),
    (0, 'White Scar', 'Citadel', 'Primer'),
    (0, 'The Fang', 'Citadel', 'Primer'),
    (0, 'Stormvermin Fur', 'Citadel', 'Primer'),
    (0, 'Averland Sunset', 'Citadel', 'Primer'),
    (0, 'Runelord Brass', 'Citadel', 'Primer'),
    (0, 'Abomination Gore', 'Army Painter', 'Paint'),
    (0, 'Alien Purple', 'Army Painter', 'Paint'),
    (0, 'Angel Green', 'Army Painter', 'Paint'),
    (0, 'Arid Earth', 'Army Painter', 'Paint'),
    (0, 'Army Green', 'Army Painter', 'Paint'),
    (0, 'Ash Grey', 'Army Painter', 'Paint'),
    (0, 'Babe Blonde', 'Army Painter', 'Paint'),
    (0, 'Banshee Brown', 'Army Painter', 'Paint'),
    (0, 'Barbarian Flesh', 'Army Painter', 'Paint'),
    (0, 'Basilisk Brown', 'Army Painter', 'Paint'),
    (0, 'Brainmatter Beige', 'Army Painter', 'Paint'),
    (0, 'Castle Grey', 'Army Painter', 'Paint'),
    (0, 'Centaur Skin', 'Army Painter', 'Paint'),
    (0, 'Chaotic Red', 'Army Painter', 'Paint'),
    (0, 'Combat Fatigue', 'Army Painter', 'Paint'),
    (0, 'Commando Green', 'Army Painter', 'Paint'),
    (0, 'Corpse Pale', 'Army Painter', 'Paint'),
    (0, 'Crusted Sore', 'Army Painter', 'Paint'),
    (0, 'Crypt Wraith', 'Army Painter', 'Paint'),
    (0, 'Crystal Blue', 'Army Painter', 'Paint'),
    (0, 'Cultist Robe', 'Army Painter', 'Paint'),
    (0, 'Daemonic Yellow', 'Army Painter', 'Paint'),
    (0, 'Dark Sky', 'Army Painter', 'Paint'),
    (0, 'Dark Stone', 'Army Painter', 'Paint'),
    (0, 'Deep Blue', 'Army Painter', 'Paint'),
    (0, 'Desert Yellow', 'Army Painter', 'Paint'),
    (0, 'Dirt Spatter', 'Army Painter', 'Paint'),
    (0, 'Dragon Red', 'Army Painter', 'Paint'),
    (0, 'Drake Tooth', 'Army Painter', 'Paint'),
    (0, 'Dungeon Grey', 'Army Painter', 'Paint'),
    (0, 'Azure Magic', 'Army Painter', 'Paint'),
    (0, 'Bright Gold', 'Army Painter', 'Metallic'),
    (0, 'Elven Armour', 'Army Painter', 'Metallic'),
    (0, 'Evil Chrome', 'Army Painter', 'Metallic'),
    (0, 'Fairy Dust', 'Army Painter', 'Metallic'),
    (0, 'Gemstone', 'Army Painter', 'Metallic'),
    (0, 'Glitter Green', 'Army Painter', 'Metallic'),
    (0, 'Greedy Gold', 'Army Painter', 'Metallic'),
    (0, 'Gun Metal', 'Army Painter', 'Metallic'),
    (0, 'Night Scales', 'Army Painter', 'Metallic'),
    (0, 'Plate Mail Metal', 'Army Painter', 'Metallic'),
    (0, 'Rough Iron', 'Army Painter', 'Metallic'),
    (0, 'Royal Purple', 'Army Painter', 'Paint'),
    (0, 'Shining Silver', 'Army Painter', 'Metallic'),
    (0, 'Tainted Gold', 'Army Painter', 'Metallic'),
    (0, 'True Copper', 'Army Painter', 'Metallic'),
    (0, 'Weapon Bronze', 'Army Painter', 'Metallic'),
    (0, 'Zephyr Pink', 'Army Painter', 'Paint'),
    (0, 'Blue Tone', 'Army Painter', 'Wash'),
    (0, 'Dark Tone', 'Army Painter', 'Wash'),
    (0, 'Flesh Wash', 'Army Painter', 'Wash'),
    (0, 'Green Tone', 'Army Painter', 'Wash'),
    (0, 'Light Tone', 'Army Painter', 'Wash'),
    (0, 'Mid Brown', 'Army Painter', 'Wash'),
    (0, 'Military Shader', 'Army Painter', 'Wash'),
    (0, 'Purple Tone', 'Army Painter', 'Wash'),
    (0, 'Red Tone', 'Army Painter', 'Wash'),
    (0, 'Soft Tone', 'Army Painter', 'Wash'),
    (0, 'Strong Tone', 'Army Painter', 'Wash'),
    (0, 'Anti-Shine Matt Varnish', 'Army Painter', 'Varnish'),
    (0, 'Brush-On Primer', 'Army Painter', 'Primer'),
    (0, 'Disgusting Slime', 'Army Painter', 'Effect'),
    (0, 'Dry Rust', 'Army Painter', 'Effect'),
    (0, 'Glistening Blood', 'Army Painter', 'Effect'),
    (0, 'Gloss Varnish', 'Army Painter', 'Varnish'),
    (0, 'Quickshade Wash Mixing Medium', 'Army Painter', 'Technical'),
    (0, 'Warpaints Mixing Medium', 'Army Painter', 'Technical'),
    (0, 'Wet Mud', 'Army Painter', 'Effect'),
    (0, 'Aegis Suit Satin Varnish', 'Army Painter', 'Varnish'),
    (0, 'Fur Brown', 'Army Painter', 'Paint'),
    (0, 'Goblin Green', 'Army Painter', 'Paint'),
    (0, 'Greenskin', 'Army Painter', 'Paint'),
    (0, 'Leather Brown', 'Army Painter', 'Paint'),
    (0, 'Matt Black Undercoat', 'Army Painter', 'Primer'),
    (0, 'Matt White Undercoat', 'Army Painter', 'Primer'),
    (0, 'Necrotic Flesh', 'Army Painter', 'Paint'),
    (0, 'Pure Red', 'Army Painter', 'Paint'),
    (0, 'Skeleton Bone', 'Army Painter', 'Paint'),
    (0, 'Ultramarine Blue', 'Army Painter', 'Paint'),
    (0, 'Uniform Grey', 'Army Painter', 'Paint'),
    (0, 'Wolf Grey', 'Army Painter', 'Paint'),
    (0, 'Absolution Green', 'Army Painter', 'Paint'),
    (0, 'Blood Red', 'Army Painter', 'Paint'),
    (0, 'Camo Cloak', 'Army Painter', 'Paint'),
    (0, 'Cloudburst Blue', 'Army Painter', 'Paint'),
    (0, 'Crusader Skin', 'Army Painter', 'Paint'),
    (0, 'Dark Wood', 'Army Painter', 'Paint'),
    (0, 'Fire Giant Orange', 'Army Painter', 'Paint'),
    (0, 'Gravelord Grey', 'Army Painter', 'Paint'),
    (0, 'Grim Black', 'Army Painter', 'Paint'),
    (0, 'Hardened Leather', 'Army Painter', 'Paint'),
    (0, 'Highlord Blue', 'Army Painter', 'Paint'),
    (0, 'Hive Dweller Purple', 'Army Painter', 'Paint'),
    (0, 'Holy White', 'Army Painter', 'Paint'),
    (0, 'Magic Blue', 'Army Painter', 'Paint'),
    (0, 'Malignant Green', 'Army Painter', 'Paint'),
    (0, 'Orc Skin', 'Army Painter', 'Paint'),
    (0, 'Pallid Bone', 'Army Painter', 'Paint'),
    (0, 'Plasmatic Bolt', 'Army Painter', 'Paint'),
    (0, 'Purple Alchemy', 'Army Painter', 'Paint'),
    (0, 'Runic Grey', 'Army Painter', 'Paint'),
    (0, 'Sand Golem', 'Army Painter', 'Paint'),
    (0, 'Slaughter Red', 'Army Painter', 'Paint'),
    (0, 'Zealot Yellow', 'Army Painter', 'Paint'),
    (0, 'Amber Skin', 'Army Painter', 'Paint'),
    (0, 'Dark Skin Wash', 'Army Painter', 'Wash'),
    (0, 'Dorado Skin', 'Army Painter', 'Paint'),
    (0, 'Garnet Pigment Toner', 'Army Painter', 'Wash'),
    (0, 'Jasper Skin', 'Army Painter', 'Paint'),
    (0, 'Mocca Skin', 'Army Painter', 'Paint'),
    (0, 'Obsidian Pigment Toner', 'Army Painter', 'Wash'),
    (0, 'Onyx Skin', 'Army Painter', 'Paint'),
    (0, 'Opal Skin', 'Army Painter', 'Paint'),
    (0, 'Pearl Pigment Toner', 'Army Painter', 'Wash'),
    (0, 'Ruby Skin', 'Army Painter', 'Paint'),
    (0, 'Soft Skin Wash', 'Army Painter', 'Wash'),
    (0, 'Strong Skin Wash', 'Army Painter', 'Wash'),
    (0, "Tiger's Eye Skin", 'Army Painter', 'Paint'),
    (0, 'Topaz Skin', 'Army Painter', 'Paint'),
    (0, 'Speedpaint Medium', 'Army Painter', 'Technical'),
    (0, 'Blinding Light', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Pastel Seafoam', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Pastel Indigo', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Princess Pink', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Pastel Salmon', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Pastel Yellow', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Burnished Red', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Lizardfolk Cyan', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Thunderbird Blue', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Rigor Mortis', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Maggot Skin', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Mummified Grime', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Howling Sand', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Aztec Gold', 'Army Painter', 'Metallic'),
    (0, 'Hoard Bronze', 'Army Painter', 'Metallic'),
    (0, 'Brazen Copper', 'Army Painter', 'Metallic'),
    (0, 'Enchanted Steel', 'Army Painter', 'Metallic'),
    (0, 'Polished Silver', 'Army Painter', 'Metallic'),
    (0, 'Glittering Loot', 'Army Painter', 'Metallic'),
    (0, 'Golden Armour', 'Army Painter', 'Metallic'),
    (0, 'Satchel Brown', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Brownish Decay', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Ochre Clay', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Ruddy Fur', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Warrior Skin', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Noble Skin', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Fire Drake', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Nuclear Sunrise', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Ancient Honey', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Maize Yellow', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Bright Red', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Murder Scene', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Poppy Red', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Carmine Dragon', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Dusk Red', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Raging Sea', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Tidal Wave', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Tyrian Navy', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Royal Robes', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Beowulf Blue', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Charming Chartreuse', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Ghoul Green', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Caribbean Ocean', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Algae Green', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Forest Sprite', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Gunner Camo', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Ghillie Dew', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Shamrock Green', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Desolate Brown', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Bony Matter', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Goddess Glow', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Peachy Flesh', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Aged Hide', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Periwinkle Purple', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Moonlake Coral', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Familiar Pink', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Moody Mauve', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Purple Swarm', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Broadsword Silver', 'Army Painter', 'Metallic'),
    (0, 'Talos Bronze', 'Army Painter', 'Metallic'),
    (0, 'Hoplite Gold', 'Army Painter', 'Metallic'),
    (0, 'Occultist Cloak', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Burnt Moss', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Ashen Stone', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Battleship Grey', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Hardened Leather', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Cloudburst Blue', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Purple Alchemy', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Sand Golem', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Plasmatic Bolt', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Hive Dweller Purple', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Fire Giant Orange', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Runic Grey', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Highlord Blue', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Magic Blue', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Zealot Yellow', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Slaughter Red', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Malignant Green', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Blood Red', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Orc Skin', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Camo Cloak', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Absolution Green', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Pallid Bone', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Dark Wood', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Crusader Skin', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Holy White', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Gravelord Grey', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'Grim Black', 'Army Painter', 'Contrast/Speed Paint'),
    (0, 'The Darkness', 'Army Painter', 'Paint'),
    (0, 'Ivory White', 'Army Painter', 'Paint'),
    (0, 'Moonbeam Yellow', 'Army Painter', 'Paint'),
    (0, 'Ironclad Grey', 'Army Painter', 'Paint'),
    (0, 'Blighted Green', 'Army Painter', 'Paint'),
    (0, 'Emperor Gold', 'Army Painter', 'Metallic'),
    (0, 'Bloodmoon Red', 'Army Painter', 'Wash'),
    (0, 'Warn Skin Shade', 'Army Painter', 'Wash'),
    (0, 'Grimdark Shadow', 'Army Painter', 'Wash'),
    (0, 'Firey Vermillion', 'Army Painter', 'Paint'),
    (0, 'Blanced Berry', 'Army Painter', 'Paint'),
    (0, 'Sunburst Ochre', 'Army Painter', 'Paint'),
    (0, 'Midnight Olive', 'Army Painter', 'Paint'),
    (0, 'Tainted Garden', 'Army Painter', 'Paint'),
    (0, 'Ruddy Terra', 'Army Painter', 'Paint'),
    (0, 'Turnbull Turquoise', 'Army Painter', 'Metallic'),
    (0, 'Voodoo Shade', 'Army Painter', 'Wash'),
    (0, 'Grim Rust', 'Army Painter', 'Effect'),
    (0, 'Bold Titanium White', 'Pro Acryl', 'Paint'),
    (0, 'Coal Black', 'Pro Acryl', 'Paint'),
    (0, 'Bold Pyrrole Red', 'Pro Acryl', 'Paint'),
    (0, 'Green', 'Pro Acryl', 'Paint'),
    (0, 'Blue', 'Pro Acryl', 'Paint'),
    (0, 'Golden Yellow', 'Pro Acryl', 'Paint'),
    (0, 'Orange', 'Pro Acryl', 'Paint'),
    (0, 'Burnt Red', 'Pro Acryl', 'Paint'),
    (0, 'Mahogany', 'Pro Acryl', 'Paint'),
    (0, 'Purple', 'Pro Acryl', 'Paint'),
    (0, 'Magenta', 'Pro Acryl', 'Paint'),
    (0, 'Sky Blue', 'Pro Acryl', 'Paint'),
    (0, 'Faded Ultramarine', 'Pro Acryl', 'Paint'),
    (0, 'Dark Grey Blue', 'Pro Acryl', 'Paint'),
    (0, 'Bright Warm Grey', 'Pro Acryl', 'Paint'),
    (0, 'Dark Warm Grey', 'Pro Acryl', 'Paint'),
    (0, 'Golden Brown', 'Pro Acryl', 'Paint'),
    (0, 'Light Umber', 'Pro Acryl', 'Paint'),
    (0, 'Dark Umber', 'Pro Acryl', 'Paint'),
    (0, 'Camo Green', 'Pro Acryl', 'Paint'),
    (0, 'Jade', 'Pro Acryl', 'Paint'),
    (0, 'Bright Ivory', 'Pro Acryl', 'Paint'),
    (0, 'Ivory', 'Pro Acryl', 'Paint'),
    (0, 'Tan Flesh', 'Pro Acryl', 'Paint'),
    (0, 'Silver', 'Pro Acryl', 'Metallic'),
    (0, 'Light Bronze', 'Pro Acryl', 'Metallic'),
    (0, 'Copper', 'Pro Acryl', 'Metallic'),
    (0, 'Rich Gold', 'Pro Acryl', 'Metallic'),
    (0, 'White Gold', 'Pro Acryl', 'Metallic'),
    (0, 'Dark Silver', 'Pro Acryl', 'Metallic'),
    (0, 'Bright Gold', 'Pro Acryl', 'Metallic'),
    (0, 'Bronze', 'Pro Acryl', 'Metallic'),
    (0, 'Metallic Medium', 'Pro Acryl', 'Technical'),
    (0, 'Dark Blue', 'Pro Acryl', 'Paint'),
    (0, 'Dark Purple', 'Pro Acryl', 'Paint'),
    (0, 'Dark Camo Green', 'Pro Acryl', 'Paint'),
    (0, 'Burnt Orange', 'Pro Acryl', 'Paint'),
    (0, 'Yellow Orche', 'Pro Acryl', 'Paint'),
    (0, 'Bright Yellow Green', 'Pro Acryl', 'Paint'),
    (0, 'Black Brown', 'Pro Acryl', 'Paint'),
    (0, 'Olive Flesh', 'Pro Acryl', 'Paint'),
    (0, 'Shadow Flesh', 'Pro Acryl', 'Paint'),
    (0, 'Pale Pink', 'Pro Acryl', 'Paint'),
    (0, 'Dark Neutral Grey', 'Pro Acryl', 'Paint'),
    (0, 'Bright Neutral Grey', 'Pro Acryl', 'Paint'),
    (0, 'Transparent Blue', 'Pro Acryl', 'Transparent/Clear'),
    (0, 'Transparent Red', 'Pro Acryl', 'Transparent/Clear'),
    (0, 'Transparent Green', 'Pro Acryl', 'Transparent/Clear'),
    (0, 'Transparent Yellow', 'Pro Acryl', 'Transparent/Clear'),
    (0, 'Transparent Orange', 'Pro Acryl', 'Transparent/Clear'),
    (0, 'Transparent Purple', 'Pro Acryl', 'Transparent/Clear'),
    (0, 'Transparent Brown', 'Pro Acryl', 'Transparent/Clear'),
    (0, 'Transparent Black', 'Pro Acryl', 'Transparent/Clear'),
    (0, 'Turquoise', 'Pro Acryl', 'Paint'),
    (0, 'Grey Blue', 'Pro Acryl', 'Paint'),
    (0, 'Blue Black', 'Pro Acryl', 'Paint'),
    (0, 'Black Green', 'Pro Acryl', 'Paint'),
    (0, 'Bright Pale Green', 'Pro Acryl', 'Paint'),
    (0, 'Burnt Sienna', 'Pro Acryl', 'Paint'),
    (0, 'Pale Yellow', 'Pro Acryl', 'Paint'),
    (0, 'Khaki', 'Pro Acryl', 'Paint'),
    (0, 'Dark Golden Brown', 'Pro Acryl', 'Paint'),
    (0, 'Faded Plum', 'Pro Acryl', 'Paint'),
    (0, 'Transparent White', 'Pro Acryl', 'Transparent/Clear'),
    (0, 'Yellow Green', 'Pro Acryl', 'Paint'),
    (0, 'Faded Green', 'Pro Acryl', 'Paint'),
    (0, 'Bright Jade', 'Pro Acryl', 'Paint'),
    (0, 'Dark Flesh', 'Pro Acryl', 'Paint'),
    (0, 'Burgundy', 'Pro Acryl', 'Paint'),
    (0, 'Plum', 'Pro Acryl', 'Paint'),
    (0, 'Pink', 'Pro Acryl', 'Paint'),
    (0, 'Warm Yellow', 'Pro Acryl', 'Paint'),
    (0, 'Warm Flesh', 'Pro Acryl', 'Paint'),
    (0, 'Warm Grey', 'Pro Acryl', 'Paint'),
    (0, 'Neutral Grey', 'Pro Acryl', 'Paint'),
    (0, 'Black wash', 'Pro Acryl', 'Wash'),
    (0, 'Brown Wash', 'Pro Acryl', 'Wash'),
    (0, 'Flesh Wash', 'Pro Acryl', 'Wash'),
    (0, 'Dark Jade', 'Pro Acryl', 'Paint'),
    (0, 'Payne’s Grey', 'Pro Acryl', 'Paint'),
    (0, 'Royal Purple', 'Pro Acryl', 'Paint'),
    (0, 'White Blue', 'Pro Acryl', 'Paint'),
    (0, 'Beige Red', 'Pro Acryl', 'Paint'),
    (0, 'Dark Yellow Green', 'Pro Acryl', 'Paint'),
    (0, 'Dark Ivory', 'Pro Acryl', 'Paint'),
    (0, 'Dark Warm Flesh', 'Pro Acryl', 'Paint'),
    (0, 'Warm Brown', 'Pro Acryl', 'Paint'),
    (0, 'Dark Magenta', 'Pro Acryl', 'Paint'),
    (0, 'Dark Plum', 'Pro Acryl', 'Paint'),
    (0, 'Red Grey', 'Pro Acryl', 'Paint'),
    (0, 'Dark Sea Ben', 'Pro Acryl', 'Paint'),
    (0, 'Petroleum Brown', 'Pro Acryl', 'Paint'),
    (0, 'Dark Burgundy', 'Pro Acryl', 'Paint'),
    (0, 'Green Oxide', 'Pro Acryl', 'Paint'),
    (0, 'Advanced Flesh Tone', 'Pro Acryl', 'Paint'),
    (0, 'Heavy Warm White', 'Pro Acryl', 'Paint'),
    (0, 'Dark Crimson', 'Pro Acryl', 'Paint'),
    (0, 'Dark Emerald', 'Pro Acryl', 'Paint'),
    (0, 'Heavy Titanium White', 'Pro Acryl', 'Paint'),
    (0, 'Brown Grey', 'Pro Acryl', 'Paint'),
    (0, 'Bone', 'Pro Acryl', 'Paint'),
    (0, 'Dark Bronze', 'Pro Acryl', 'Metallic'),
    (0, 'Red Oxide', 'Pro Acryl', 'Paint'),
    (0, 'Orange Oxide', 'Pro Acryl', 'Paint'),
    (0, 'Satin Black', 'Pro Acryl', 'Paint'),
    (0, 'Drab Brown', 'Pro Acryl', 'Paint'),
    (0, 'Bright Shadow Flesh', 'Pro Acryl', 'Paint'),
    (0, 'Magnesium', 'Pro Acryl', 'Metallic'),
    (0, 'PRIME 002 - Black', 'Pro Acryl', 'Primer'),
    (0, 'PRIME 003 - White', 'Pro Acryl', 'Primer'),
    (0, 'PRIME 005 - Dark Neutral Grey', 'Pro Acryl', 'Primer'),
    (0, 'PRIME 007 - Dark Camo Green', 'Pro Acryl', 'Primer'),
    (0, 'PRIME 011 - Black Brown', 'Pro Acryl', 'Primer'),
    (0, "Goon's Grime", 'Villainy Inks', 'Wash'),
    (0, 'Sector Rust', 'Villainy Inks', 'Wash'),
    (0, 'Coelia Green', 'Villainy Inks', 'Effect'),
    (0, 'Carrion Crimson', 'Villainy Inks', 'Effect'),
    (0, 'Ichor of the Damned', 'Villainy Inks', 'Effect'),
    (0, 'Dystopian Brown', 'Villainy Inks', 'Effect'),
    (0, 'Decay of Death', 'Villainy Inks', 'Wash'),
    (0, 'Decrepit Filth', 'Villainy Inks', 'Wash'),
    (0, 'Umbral Nightshade', 'Villainy Inks', 'Effect'),
    (0, 'Caput Mortuum', 'Villainy Inks', 'Effect'),
    (0, 'Vile Tinge Green', 'Villainy Inks', 'Wash'),
    (0, 'Blighted Bone Ochre', 'Villainy Inks', 'Wash'),
    (0, '-Ex- Machina', 'Villainy Inks', 'Effect'),
    (0, 'All Is Dust', 'Villainy Inks', 'Wash'),
    (0, 'Black', 'Scale 75', 'Paint'),
    (0, 'White', 'Scale 75', 'Paint'),
    (0, 'Nacar', 'Scale 75', 'Paint'),
    (0, 'Graphite', 'Scale 75', 'Paint'),
    (0, 'Anthracite Gray', 'Scale 75', 'Paint'),
    (0, 'Artic Blue', 'Scale 75', 'Paint'),
    (0, 'Bering Blue', 'Scale 75', 'Paint'),
    (0, 'Caspian Blue', 'Scale 75', 'Paint'),
    (0, 'Abyssal Blue', 'Scale 75', 'Paint'),
    (0, 'White sands', 'Scale 75', 'Paint'),
    (0, 'Tenere yellow', 'Scale 75', 'Paint'),
    (0, 'Sahara yellow', 'Scale 75', 'Paint'),
    (0, 'Gobi brown', 'Scale 75', 'Paint'),
    (0, 'Dubai brown', 'Scale 75', 'Paint'),
    (0, 'Kalahari orange', 'Scale 75', 'Paint'),
    (0, 'Adriatic blue', 'Scale 75', 'Paint'),
    (0, 'Eclipse grey', 'Scale 75', 'Paint'),
    (0, 'Pale skin', 'Scale 75', 'Paint'),
    (0, 'Light skin', 'Scale 75', 'Paint'),
    (0, 'Golden skin', 'Scale 75', 'Paint'),
    (0, 'Basic flesh', 'Scale 75', 'Paint'),
    (0, 'Pink flesh', 'Scale 75', 'Paint'),
    (0, 'Arabic shadow', 'Scale 75', 'Paint'),
    (0, 'Indian shadow', 'Scale 75', 'Paint'),
    (0, 'African shadow', 'Scale 75', 'Paint'),
    (0, 'Birch', 'Scale 75', 'Paint'),
    (0, 'Sandal wood', 'Scale 75', 'Paint'),
    (0, 'Iroko', 'Scale 75', 'Paint'),
    (0, 'Orange leather', 'Scale 75', 'Paint'),
    (0, 'Walnut', 'Scale 75', 'Paint'),
    (0, 'red leather', 'Scale 75', 'Paint'),
    (0, 'Brown leather', 'Scale 75', 'Paint'),
    (0, 'Black leather', 'Scale 75', 'Paint'),
    (0, 'Sunset purple', 'Scale 75', 'Paint'),
    (0, 'Fushsia', 'Scale 75', 'Paint'),
    (0, 'Deep red', 'Scale 75', 'Paint'),
    (0, 'Blood red', 'Scale 75', 'Paint'),
    (0, 'Antares red', 'Scale 75', 'Paint'),
    (0, 'Aldebaran red', 'Scale 75', 'Paint'),
    (0, 'Mars orange', 'Scale 75', 'Paint'),
    (0, 'Sol yellow', 'Scale 75', 'Paint'),
    (0, 'Black forest green', 'Scale 75', 'Paint'),
    (0, 'Boreal green', 'Scale 75', 'Paint'),
    (0, 'Irati green', 'Scale 75', 'Paint'),
    (0, 'Sherwood green', 'Scale 75', 'Paint'),
    (0, 'Ardennes green', 'Scale 75', 'Paint'),
    (0, 'Field gray', 'Scale 75', 'Paint'),
    (0, 'Spring green', 'Scale 75', 'Paint'),
    (0, 'Fall green', 'Scale 75', 'Paint'),
    (0, 'Caribbean blue', 'Scale 75', 'Paint'),
    (0, 'Sky blue', 'Scale 75', 'Paint'),
    (0, 'Mediterranean blue', 'Scale 75', 'Paint'),
    (0, 'Tesla blue', 'Scale 75', 'Paint'),
    (0, 'Cantabric blue', 'Scale 75', 'Paint'),
    (0, 'Navy blue', 'Scale 75', 'Paint'),
    (0, 'Deep blue', 'Scale 75', 'Paint'),
    (0, 'Violet', 'Scale 75', 'Paint'),
    (0, 'Petroleum Gray', 'Scale 75', 'Paint'),
    (0, 'Graphene gray', 'Scale 75', 'Paint'),
    (0, 'Brown gray', 'Scale 75', 'Paint'),
    (0, 'Rainy gray', 'Scale 75', 'Paint'),
    (0, 'Thar brown', 'Scale 75', 'Paint'),
    (0, 'Mojave white', 'Scale 75', 'Paint'),
    (0, 'Decay Black', 'Scale 75', 'Paint'),
    (0, 'Purity White', 'Scale 75', 'Paint'),
    (0, 'Hastur Purple', 'Scale 75', 'Paint'),
    (0, 'Mayhem Red', 'Scale 75', 'Paint'),
    (0, 'Baal Crimson', 'Scale 75', 'Paint'),
    (0, 'Beherit red', 'Scale 75', 'Paint'),
    (0, 'Tiamat Orange', 'Scale 75', 'Paint'),
    (0, 'Ishtar Pink', 'Scale 75', 'Paint'),
    (0, 'Marduck Yellow', 'Scale 75', 'Paint'),
    (0, 'Lilith Yellow', 'Scale 75', 'Paint'),
    (0, 'Misfits Green', 'Scale 75', 'Paint'),
    (0, 'Bloodfest Crimson', 'Scale 75', 'Paint'),
    (0, 'Braineater Azure', 'Scale 75', 'Paint'),
    (0, 'Undead Flesh', 'Scale 75', 'Paint'),
    (0, 'Resurrection Flesh', 'Scale 75', 'Paint'),
    (0, 'Harvester Flesh', 'Scale 75', 'Paint'),
    (0, 'Hellbound Flesh', 'Scale 75', 'Paint'),
    (0, 'Moonray Flesh', 'Scale 75', 'Paint'),
    (0, 'Riff Green', 'Scale 75', 'Paint'),
    (0, 'Orcish Dermis', 'Scale 75', 'Paint'),
    (0, 'Merm Green', 'Scale 75', 'Paint'),
    (0, 'Greenskin Flesh', 'Scale 75', 'Paint'),
    (0, 'Goblin Flesh', 'Scale 75', 'Paint'),
    (0, 'Ogre Flesh', 'Scale 75', 'Paint'),
    (0, 'Elven Flesh', 'Scale 75', 'Paint'),
    (0, 'Troll Flesh', 'Scale 75', 'Paint'),
    (0, 'Ghoul Flesh', 'Scale 75', 'Paint'),
    (0, 'Vampire Flesh', 'Scale 75', 'Paint'),
    (0, 'Gnome Flesh', 'Scale 75', 'Paint'),
    (0, 'Dwarf Flesh', 'Scale 75', 'Paint'),
    (0, 'Draconic Flesh', 'Scale 75', 'Paint'),
    (0, 'Orc Flesh', 'Scale 75', 'Paint'),
    (0, 'Giant Flesh', 'Scale 75', 'Paint'),
    (0, 'Troll Skin', 'Scale 75', 'Paint'),
    (0, 'Goblin Skin', 'Scale 75', 'Paint'),
    (0, 'Ogre Skin', 'Scale 75', 'Paint'),
    (0, 'Dwarven Skin', 'Scale 75', 'Paint'),
    (0, 'Elven Skin', 'Scale 75', 'Paint'),
    (0, 'Orc Skin', 'Scale 75', 'Paint'),
    (0, 'Giant Skin', 'Scale 75', 'Paint'),
    (0, 'Vampire Skin', 'Scale 75', 'Paint'),
    (0, 'Ghoul Skin', 'Scale 75', 'Paint'),
    (0, 'Draconic Skin', 'Scale 75', 'Paint'),
    (0, 'Gnome Skin', 'Scale 75', 'Paint'),
    (0, 'Black metal', 'Scale 75', 'Metallic'),
    (0, 'Trash metal', 'Scale 75', 'Metallic'),
    (0, 'Heavy metal', 'Scale 75', 'Metallic'),
    (0, 'Speed metal', 'Scale 75', 'Metallic'),
    (0, 'White alchemy', 'Scale 75', 'Paint'),
    (0, 'Cobalt alchemy', 'Scale 75', 'Paint'),
    (0, 'Emerald alchemy', 'Scale 75', 'Paint'),
    (0, 'Amethyst alchemy', 'Scale 75', 'Paint'),
    (0, 'Necro gold', 'Scale 75', 'Metallic'),
    (0, 'Viking gold', 'Scale 75', 'Metallic'),
    (0, 'Dwarven gold', 'Scale 75', 'Metallic'),
    (0, 'Elven gold', 'Scale 75', 'Metallic'),
    (0, 'Citrine alchemy', 'Scale 75', 'Paint'),
    (0, 'Tourmaline alchemy', 'Scale 75', 'Paint'),
    (0, 'Kunzite alchemy', 'Scale 75', 'Paint'),
    (0, 'Peridot alchemy', 'Scale 75', 'Paint'),
    (0, 'Inktense Black', 'Scale 75', 'Wash'),
    (0, 'Inktense Wood', 'Scale 75', 'Wash'),
    (0, 'Inktense Chesnut', 'Scale 75', 'Wash'),
    (0, 'Inktense violet', 'Scale 75', 'Wash'),
    (0, 'Inktense Blue', 'Scale 75', 'Wash'),
    (0, 'Inktense Green', 'Scale 75', 'Wash'),
    (0, 'Inktense Red', 'Scale 75', 'Wash'),
    (0, 'Inktense Yellow', 'Scale 75', 'Wash'),
    (0, 'Decayed Metal', 'Scale 75', 'Metallic'),
    (0, 'Old Copper', 'Scale 75', 'Metallic'),
    (0, 'Garnet Alchemy', 'Scale 75', 'Paint'),
    (0, 'Ruby Alchemy', 'Scale 75', 'Paint'),
    (0, 'Pure Copper', 'Scale 75', 'Metallic'),
    (0, 'Victorian Brass', 'Scale 75', 'Metallic'),
    (0, 'Amber Alchemy', 'Scale 75', 'Paint'),
    (0, 'Moonstone Alchemy', 'Scale 75', 'Paint'),
    (0, 'Inktense Brown', 'Scale 75', 'Wash'),
    (0, 'Inktense Crimson', 'Scale 75', 'Wash'),
    (0, 'Inktense Oxide', 'Scale 75', 'Wash'),
    (0, 'Inktense Ochre', 'Scale 75', 'Wash'),
    (0, 'Inktense Cyan', 'Scale 75', 'Wash'),
    (0, 'Inktense Lime', 'Scale 75', 'Wash'),
    (0, 'Inktense Olive', 'Scale 75', 'Wash'),
    (0, 'Inktense White', 'Scale 75', 'Wash'),
    (0, 'Black', 'Scale 75', 'Primer'),
    (0, 'White', 'Scale 75', 'Primer'),
    (0, 'Grey', 'Scale 75', 'Primer'),
    (0, 'Matt Black', 'Scale 75', 'Primer'),
    (0, 'Matt White', 'Scale 75', 'Primer'),
    (0, 'Matt Grey', 'Scale 75', 'Primer'),
    (0, 'Gloss Black', 'Scale 75', 'Primer'),
    (0, 'Gloss White', 'Scale 75', 'Primer'),
    (0, 'Gloss Grey', 'Scale 75', 'Primer'),
    (0, 'Soil Works: Sand', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Earth', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Grass', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Snow', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Ash', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Mud', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Rock', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Sand', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Earth', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Grass', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Snow', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Ash', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Mud', 'Scale 75', 'Texture'),
    (0, 'Soil Works: Rock', 'Scale 75', 'Texture'),
    (0, 'FX Fluor Experience: Red', 'Scale 75', 'Paint'),
    (0, 'FX Fluor Experience: Orange', 'Scale 75', 'Paint'),
    (0, 'FX Fluor Experience: Yellow', 'Scale 75', 'Paint'),
    (0, 'FX Fluor Experience: Green', 'Scale 75', 'Paint'),
    (0, 'FX Fluor Experience: Blue', 'Scale 75', 'Paint'),
    (0, 'FX Fluor Experience: Violet', 'Scale 75', 'Paint'),
    (0, 'FX Fluor Experience: Pink', 'Scale 75', 'Paint'),
    (0, 'FX Fluor Experience: White', 'Scale 75', 'Paint'),
    (0, 'Warfront: German Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: Russian Green', 'Scale 75', 'Paint'),
    (0, 'Warfront: US Olive Drab', 'Scale 75', 'Paint'),
    (0, 'Warfront: British Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: French Blue', 'Scale 75', 'Paint'),
    (0, 'Warfront: Japanese Green', 'Scale 75', 'Paint'),
    (0, 'Warfront: Italian Brown', 'Scale 75', 'Paint'),
    (0, 'Warfront: Polish Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: Canadian Green', 'Scale 75', 'Paint'),
    (0, 'Warfront: Australian Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: Romanian Brown', 'Scale 75', 'Paint'),
    (0, 'Warfront: Hungarian Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: Finnish White', 'Scale 75', 'Paint'),
    (0, 'Warfront: Yugoslavian Green', 'Scale 75', 'Paint'),
    (0, 'Warfront: Greek Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: Dutch Brown', 'Scale 75', 'Paint'),
    (0, 'Warfront: Belgian Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: Turkish Brown', 'Scale 75', 'Paint'),
    (0, 'Warfront: Portuguese Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: Spanish Green', 'Scale 75', 'Paint'),
    (0, 'Warfront: Swedish Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: Swiss Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: Austrian Brown', 'Scale 75', 'Paint'),
    (0, 'Warfront: Norwegian Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: Danish Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: Irish Green', 'Scale 75', 'Paint'),
    (0, 'Warfront: Icelandic Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: Luxembourg Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: Liechtenstein Brown', 'Scale 75', 'Paint'),
    (0, 'Warfront: Monaco Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: San Marino Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: Andorra Green', 'Scale 75', 'Paint'),
    (0, 'Warfront: Malta Brown', 'Scale 75', 'Paint'),
    (0, 'Warfront: Cyprus Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: Vatican Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: Liechtenstein Brown', 'Scale 75', 'Paint'),
    (0, 'Warfront: Monaco Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: San Marino Khaki', 'Scale 75', 'Paint'),
    (0, 'Warfront: Andorra Green', 'Scale 75', 'Paint'),
    (0, 'Warfront: Malta Brown', 'Scale 75', 'Paint'),
    (0, 'Warfront: Cyprus Grey', 'Scale 75', 'Paint'),
    (0, 'Warfront: Vatican Khaki', 'Scale 75', 'Paint'),
    (0, 'Instant Color: Black', 'Scale 75', 'Contrast/Speed Paint'),
    (0, 'Instant Color: White', 'Scale 75', 'Contrast/Speed Paint'),
    (0, 'Instant Color: Red', 'Scale 75', 'Contrast/Speed Paint'),
    (0, 'Instant Color: Blue', 'Scale 75', 'Contrast/Speed Paint'),
    (0, 'Instant Color: Green', 'Scale 75', 'Contrast/Speed Paint'),
    (0, 'Instant Color: Yellow', 'Scale 75', 'Contrast/Speed Paint'),
    (0, 'Instant Color: Orange', 'Scale 75', 'Contrast/Speed Paint'),
    (0, 'Instant Color: Purple', 'Scale 75', 'Contrast/Speed Paint'),
    (0, 'Matt White', 'Colour Forge', 'Primer'),
    (0, 'Wight Bone', 'Colour Forge', 'Primer'),
    (0, 'Ossified Earth', 'Colour Forge', 'Primer'),
    (0, 'Desert Sand', 'Colour Forge', 'Primer'),
    (0, 'Sunset Yellow', 'Colour Forge', 'Primer'),
    (0, 'Sanguine Red', 'Colour Forge', 'Primer'),
    (0, 'Convict Orange', 'Colour Forge', 'Primer'),
    (0, 'Governor Green', 'Colour Forge', 'Primer'),
    (0, 'Renegade Green', 'Colour Forge', 'Primer'),
    (0, 'Salamander Green', 'Colour Forge', 'Primer'),
    (0, 'Death Rattle Green', 'Colour Forge', 'Primer'),
    (0, 'Imperial Purple', 'Colour Forge', 'Primer'),
    (0, 'Republic Blue', 'Colour Forge', 'Primer'),
    (0, 'Tempest Blue', 'Colour Forge', 'Primer'),
    (0, 'Trench Brown', 'Colour Forge', 'Primer'),
    (0, 'Hyrax Brown', 'Colour Forge', 'Primer'),
    (0, 'Standard Grey', 'Colour Forge', 'Primer'),
    (0, 'Wolfkin Grey', 'Colour Forge', 'Primer'),
    (0, 'Ghoul Grey', 'Colour Forge', 'Primer'),
    (0, 'Matt Black', 'Colour Forge', 'Primer'),
    (0, 'Raven Black', 'Colour Forge', 'Primer'),
    (0, 'Steelforge Silver', 'Colour Forge', 'Primer'),
    (0, 'Gauntlet Gold', 'Colour Forge', 'Primer'),
    (0, 'Reliquary Red', 'Colour Forge', 'Primer'),
    (0, 'Valrak Yellow', 'Colour Forge', 'Primer'),
    (0, 'Peachy Peach', 'Colour Forge', 'Primer'),
    (0, 'Midwinter Ice', 'Colour Forge', 'Primer'),
    (0, 'Rogue Pink', 'Colour Forge', 'Primer'),
    (0, 'Ashen Grey', 'Colour Forge', 'Primer'),
    (0, 'Dead Animal Bits', 'Colour Forge', 'Primer'),
    (0, 'Seige Armour', 'Colour Forge', 'Primer'),
    (0, 'Matt Varnish', 'Colour Forge', 'Varnish'),
    (0, 'MDF Sealer', 'Colour Forge', 'Primer'),
    (0, 'White', 'AK Interactive', 'Paint'),
    (0, 'Off White', 'AK Interactive', 'Paint'),
    (0, 'White Grey', 'AK Interactive', 'Paint'),
    (0, 'Ivory', 'AK Interactive', 'Paint'),
    (0, 'Greenish White', 'AK Interactive', 'Paint'),
    (0, 'Silver Grey', 'AK Interactive', 'Paint'),
    (0, 'Rock Grey', 'AK Interactive', 'Paint'),
    (0, 'Grimy Grey', 'AK Interactive', 'Paint'),
    (0, 'Warm Grey', 'AK Interactive', 'Paint'),
    (0, 'Medium Grey', 'AK Interactive', 'Paint'),
    (0, 'Blue-Grey', 'AK Interactive', 'Paint'),
    (0, 'Sky Grey', 'AK Interactive', 'Paint'),
    (0, 'Pale Grey', 'AK Interactive', 'Paint'),
    (0, 'Medium Sea Grey', 'AK Interactive', 'Paint'),
    (0, 'Dark Sea Grey', 'AK Interactive', 'Paint'),
    (0, 'Grey-Green', 'AK Interactive', 'Paint'),
    (0, 'Reddish Grey', 'AK Interactive', 'Paint'),
    (0, 'Neutral Grey', 'AK Interactive', 'Paint'),
    (0, 'Graphite', 'AK Interactive', 'Paint'),
    (0, 'English Grey', 'AK Interactive', 'Paint'),
    (0, 'Basalt Grey', 'AK Interactive', 'Paint'),
    (0, 'Dark Grey', 'AK Interactive', 'Paint'),
    (0, 'Lead Grey', 'AK Interactive', 'Paint'),
    (0, 'Ash Grey', 'AK Interactive', 'Paint'),
    (0, 'German Grey', 'AK Interactive', 'Paint'),
    (0, 'Tenebrous Grey', 'AK Interactive', 'Paint'),
    (0, 'Rubber Black', 'AK Interactive', 'Paint'),
    (0, 'Smoke Black', 'AK Interactive', 'Paint'),
    (0, 'Black', 'AK Interactive', 'Paint'),
    (0, 'Beige', 'AK Interactive', 'Paint'),
    (0, 'Buff', 'AK Interactive', 'Paint'),
    (0, 'Pale Sand', 'AK Interactive', 'Paint'),
    (0, 'Dark Sand', 'AK Interactive', 'Paint'),
    (0, 'Medium Sand', 'AK Interactive', 'Paint'),
    (0, 'Sand Yellow', 'AK Interactive', 'Paint'),
    (0, 'Ice Yellow', 'AK Interactive', 'Paint'),
    (0, 'Pastel Yellow', 'AK Interactive', 'Paint'),
    (0, 'Pale Yellow', 'AK Interactive', 'Paint'),
    (0, 'Purulent Yellow', 'AK Interactive', 'Paint'),
    (0, 'Sahara Yellow', 'AK Interactive', 'Paint'),
    (0, 'Golden Yellow', 'AK Interactive', 'Paint'),
    (0, 'Volcanic Yellow', 'AK Interactive', 'Paint'),
    (0, 'Dirty Yellow', 'AK Interactive', 'Paint'),
    (0, 'Yellow', 'AK Interactive', 'Paint'),
    (0, 'Deep Yellow', 'AK Interactive', 'Paint'),
    (0, 'Radiant Yellow', 'AK Interactive', 'Paint'),
    (0, 'Lemon Yellow', 'AK Interactive', 'Paint'),
    (0, 'Laser Yellow', 'AK Interactive', 'Paint'),
    (0, 'Fluorescent Yellow', 'AK Interactive', 'Paint'),
    (0, 'Light Flesh', 'AK Interactive', 'Paint'),
    (0, 'Luminous Flesh', 'AK Interactive', 'Paint'),
    (0, 'Basic Skin Tone', 'AK Interactive', 'Paint'),
    (0, 'Radiant Flesh', 'AK Interactive', 'Paint'),
    (0, 'Medium Flesh Tone', 'AK Interactive', 'Paint'),
    (0, 'Sunny Skin Tone', 'AK Interactive', 'Paint'),
    (0, 'Dark Flesh', 'AK Interactive', 'Paint'),
    (0, 'Vampiric Flesh', 'AK Interactive', 'Paint'),
    (0, 'Decomposed Flesh', 'AK Interactive', 'Paint'),
    (0, 'Pastel Pink', 'AK Interactive', 'Paint'),
    (0, 'Sickly Pink', 'AK Interactive', 'Paint'),
    (0, 'Salmon', 'AK Interactive', 'Paint'),
    (0, 'Old Rose', 'AK Interactive', 'Paint'),
    (0, 'Brown Rose', 'AK Interactive', 'Paint'),
    (0, 'Beige Red', 'AK Interactive', 'Paint'),
    (0, 'Intense Pink', 'AK Interactive', 'Paint'),
    (0, 'Laser Magenta', 'AK Interactive', 'Paint'),
    (0, 'Magenta', 'AK Interactive', 'Paint'),
    (0, 'Fluorescent Magenta', 'AK Interactive', 'Paint'),
    (0, 'Pastel Violet', 'AK Interactive', 'Paint'),
    (0, 'Blue Violet', 'AK Interactive', 'Paint'),
    (0, 'Lilac', 'AK Interactive', 'Paint'),
    (0, 'Deep Violet', 'AK Interactive', 'Paint'),
    (0, 'Purple', 'AK Interactive', 'Paint'),
    (0, 'Deep Purple', 'AK Interactive', 'Paint'),
    (0, 'Violet Red', 'AK Interactive', 'Paint'),
    (0, 'Pastel Peach', 'AK Interactive', 'Paint'),
    (0, 'Light Orange', 'AK Interactive', 'Paint'),
    (0, 'Medium Orange', 'AK Interactive', 'Paint'),
    (0, 'Burn Orange', 'AK Interactive', 'Paint'),
    (0, 'Deep Orange', 'AK Interactive', 'Paint'),
    (0, 'Fluorescent Orange', 'AK Interactive', 'Paint'),
    (0, 'Luminous Orange', 'AK Interactive', 'Paint'),
    (0, 'Dead Orange', 'AK Interactive', 'Paint'),
    (0, 'Ruby', 'AK Interactive', 'Paint'),
    (0, 'Cadmium Red', 'AK Interactive', 'Paint'),
    (0, 'Amaranth Red', 'AK Interactive', 'Paint'),
    (0, 'Scarlet Red', 'AK Interactive', 'Paint'),
    (0, 'Deep Red', 'AK Interactive', 'Paint'),
    (0, 'Blood Red', 'AK Interactive', 'Paint'),
    (0, 'Vermillion', 'AK Interactive', 'Paint'),
    (0, 'Carmine', 'AK Interactive', 'Paint'),
    (0, 'Matt Red', 'AK Interactive', 'Paint'),
    (0, 'Brick Red', 'AK Interactive', 'Paint'),
    (0, 'Bordeaux Red', 'AK Interactive', 'Paint'),
    (0, 'Dirty Red', 'AK Interactive', 'Paint'),
    (0, 'Wine Red', 'AK Interactive', 'Paint'),
    (0, 'Burnt Red', 'AK Interactive', 'Paint'),
    (0, 'Black Red', 'AK Interactive', 'Paint'),
    (0, 'Ocher Orange', 'AK Interactive', 'Paint'),
    (0, 'Light Brown', 'AK Interactive', 'Paint'),
    (0, 'Orange Brown', 'AK Interactive', 'Paint'),
    (0, 'Deep Brown', 'AK Interactive', 'Paint'),
    (0, 'Medium Rust', 'AK Interactive', 'Paint'),
    (0, 'Saddle Brown', 'AK Interactive', 'Paint'),
    (0, 'Light Rust', 'AK Interactive', 'Paint'),
    (0, 'Mahogany Brown', 'AK Interactive', 'Paint'),
    (0, 'Dark Rust', 'AK Interactive', 'Paint'),
    (0, 'Hull Red', 'AK Interactive', 'Paint'),
    (0, 'Dark Brown', 'AK Interactive', 'Paint'),
    (0, 'Leather Brown', 'AK Interactive', 'Paint'),
    (0, 'Burnt Umber', 'AK Interactive', 'Paint'),
    (0, 'Grim Brown', 'AK Interactive', 'Paint'),
    (0, 'Chocolate (Chipping)', 'AK Interactive', 'Paint'),
    (0, 'Deck Tan', 'AK Interactive', 'Paint'),
    (0, 'Light Earth', 'AK Interactive', 'Paint'),
    (0, 'Tan Yellow', 'AK Interactive', 'Paint'),
    (0, 'Golden Brown', 'AK Interactive', 'Paint'),
    (0, 'Ocher', 'AK Interactive', 'Paint'),
    (0, 'Cork', 'AK Interactive', 'Paint'),
    (0, 'Mud Brown', 'AK Interactive', 'Paint'),
    (0, 'Tan Earth', 'AK Interactive', 'Paint'),
    (0, 'Green Ocher', 'AK Interactive', 'Paint'),
    (0, 'Japanese Brown', 'AK Interactive', 'Paint'),
    (0, 'Middle Stone', 'AK Interactive', 'Paint'),
    (0, 'Grey-Brown', 'AK Interactive', 'Paint'),
    (0, 'Green-Brown', 'AK Interactive', 'Paint'),
    (0, 'British Khaki', 'AK Interactive', 'Paint'),
    (0, 'Luminous Green', 'AK Interactive', 'Paint'),
    (0, 'Fluorescent Green', 'AK Interactive', 'Paint'),
    (0, 'Pistachio', 'AK Interactive', 'Paint'),
    (0, 'Pastel Green', 'AK Interactive', 'Paint'),
    (0, 'Green-Grey', 'AK Interactive', 'Paint'),
    (0, 'Dark Green-Grey', 'AK Interactive', 'Paint'),
    (0, 'Green Sky', 'AK Interactive', 'Paint'),
    (0, 'Faded Green', 'AK Interactive', 'Paint'),
    (0, 'Frog Green', 'AK Interactive', 'Paint'),
    (0, 'Lime Green', 'AK Interactive', 'Paint'),
    (0, 'Interior Yellow Green', 'AK Interactive', 'Paint'),
    (0, 'Golden Olive', 'AK Interactive', 'Paint'),
    (0, 'Grass Green', 'AK Interactive', 'Paint'),
    (0, 'Light Green', 'AK Interactive', 'Paint'),
    (0, 'Deep Green', 'AK Interactive', 'Paint'),
    (0, 'Mint Green', 'AK Interactive', 'Paint'),
    (0, 'Emerald', 'AK Interactive', 'Paint'),
    (0, 'Lizard Green', 'AK Interactive', 'Paint'),
    (0, 'Dark Green', 'AK Interactive', 'Paint'),
    (0, 'Olive Green', 'AK Interactive', 'Paint'),
    (0, 'Medium Olive Green', 'AK Interactive', 'Paint'),
    (0, 'Intermediate Green', 'AK Interactive', 'Paint'),
    (0, 'Gunship Green', 'AK Interactive', 'Paint'),
    (0, 'Brownish Green', 'AK Interactive', 'Paint'),
    (0, 'Alga Green', 'AK Interactive', 'Paint'),
    (0, 'Extra Dark Green', 'AK Interactive', 'Paint'),
    (0, 'German Field Grey', 'AK Interactive', 'Paint'),
    (0, 'Command Green', 'AK Interactive', 'Paint'),
    (0, 'Camouflage Green', 'AK Interactive', 'Paint'),
    (0, 'US Dark Green', 'AK Interactive', 'Paint'),
    (0, 'Reflective Green', 'AK Interactive', 'Paint'),
    (0, 'Russian Green', 'AK Interactive', 'Paint'),
    (0, 'Black Green', 'AK Interactive', 'Paint'),
    (0, 'Pale Blue', 'AK Interactive', 'Paint'),
    (0, 'Spectrum Blue', 'AK Interactive', 'Paint'),
    (0, 'Intermediate Blue', 'AK Interactive', 'Paint'),
    (0, 'Dark Blue-Grey', 'AK Interactive', 'Paint'),
    (0, 'Grey-Blue', 'AK Interactive', 'Paint'),
    (0, 'French Blue', 'AK Interactive', 'Paint'),
    (0, 'Anthracite Grey', 'AK Interactive', 'Paint'),
    (0, 'Pastel Blue', 'AK Interactive', 'Paint'),
    (0, 'Blue-Green', 'AK Interactive', 'Paint'),
    (0, 'Aquatic Turquoise', 'AK Interactive', 'Paint'),
    (0, 'Turquoise', 'AK Interactive', 'Paint'),
    (0, 'Archaic Turquoise', 'AK Interactive', 'Paint'),
    (0, 'Ocean Blue', 'AK Interactive', 'Paint'),
    (0, 'Snow Blue', 'AK Interactive', 'Paint'),
    (0, 'Sky Blue', 'AK Interactive', 'Paint'),
    (0, 'Deep Sky Blue', 'AK Interactive', 'Paint'),
    (0, 'Ducat Blue', 'AK Interactive', 'Paint'),
    (0, 'Fluorescent Blue', 'AK Interactive', 'Paint'),
    (0, 'Ultramarine', 'AK Interactive', 'Paint'),
    (0, 'Imperial Blue', 'AK Interactive', 'Paint'),
    (0, 'Dark Blue', 'AK Interactive', 'Paint'),
    (0, 'Deep Blue', 'AK Interactive', 'Paint'),
    (0, 'Amethyst Blue', 'AK Interactive', 'Paint'),
    (0, 'Medium Blue', 'AK Interactive', 'Paint'),
    (0, 'Star Blue', 'AK Interactive', 'Paint'),
    (0, 'Light Prussian Blue', 'AK Interactive', 'Paint'),
    (0, 'Strong Dark Blue', 'AK Interactive', 'Paint'),
    (0, 'Oxford', 'AK Interactive', 'Paint'),
    (0, 'Dark Prussian Blue', 'AK Interactive', 'Paint'),
    (0, 'Dark Sea Blue', 'AK Interactive', 'Paint'),
    (0, 'Gold', 'AK Interactive', 'Metallic'),
    (0, 'Old Gold', 'AK Interactive', 'Metallic'),
    (0, 'Rusty Gold', 'AK Interactive', 'Metallic'),
    (0, 'Brass', 'AK Interactive', 'Metallic'),
    (0, 'Rusty Brass', 'AK Interactive', 'Metallic'),
    (0, 'Bronze', 'AK Interactive', 'Metallic'),
    (0, 'Copper', 'AK Interactive', 'Metallic'),
    (0, 'Burnt Tin', 'AK Interactive', 'Metallic'),
    (0, 'Metallic Blue', 'AK Interactive', 'Metallic'),
    (0, 'Astral Beryllium', 'AK Interactive', 'Metallic'),
    (0, 'Cobalt Blue', 'AK Interactive', 'Metallic'),
    (0, 'Anodized Violet', 'AK Interactive', 'Metallic'),
    (0, 'Foundry Red', 'AK Interactive', 'Metallic'),
    (0, 'Emerald Metallic Green', 'AK Interactive', 'Metallic'),
    (0, 'Metallic Green', 'AK Interactive', 'Metallic'),
    (0, 'Pearl', 'AK Interactive', 'Metallic'),
    (0, 'Aluminium', 'AK Interactive', 'Metallic'),
    (0, 'Dark Aluminium', 'AK Interactive', 'Metallic'),
    (0, 'Silver', 'AK Interactive', 'Metallic'),
    (0, 'Natural Steel', 'AK Interactive', 'Metallic'),
    (0, 'Oily Steel', 'AK Interactive', 'Metallic'),
    (0, 'Gun Metal', 'AK Interactive', 'Metallic'),
    (0, 'Clear Red', 'AK Interactive', 'Transparent/Clear'),
    (0, 'Clear Blue', 'AK Interactive', 'Transparent/Clear'),
    (0, 'Clear Smoke', 'AK Interactive', 'Transparent/Clear'),
    (0, 'Clear Green', 'AK Interactive', 'Transparent/Clear'),
    (0, 'Clear Yellow', 'AK Interactive', 'Transparent/Clear'),
    (0, 'Clear Orange', 'AK Interactive', 'Transparent/Clear'),
    (0, 'Sepia Ink', 'AK Interactive', 'Ink'),
    (0, 'Turquoise Ink', 'AK Interactive', 'Ink'),
    (0, 'Skin Ink', 'AK Interactive', 'Ink'),
    (0, 'Sooty Black Ink', 'AK Interactive', 'Ink'),
    (0, 'Carbon Black Ink', 'AK Interactive', 'Ink'),
    (0, 'Purple Ink', 'AK Interactive', 'Ink'),
    (0, 'Luminous Green Ink', 'AK Interactive', 'Ink'),
    (0, 'Dark Green Ink', 'AK Interactive', 'Ink'),
    (0, 'Penetrating Red Ink', 'AK Interactive', 'Ink'),
    (0, 'Night Blue Ink', 'AK Interactive', 'Ink'),
    (0, 'Burnt Umber Ink', 'AK Interactive', 'Ink'),
    (0, 'Titanium White Ink', 'AK Interactive', 'Ink'),
    (0, 'Retarder', 'AK Interactive', 'Technical'),
    (0, 'Metal Medium', 'AK Interactive', 'Technical'),
    (0, 'Glaze Medium', 'AK Interactive', 'Technical'),
    (0, 'Matte Medium', 'AK Interactive', 'Technical'),
    (0, 'Gloss Medium', 'AK Interactive', 'Technical'),
    (0, 'Crackle Medium', 'AK Interactive', 'Technical'),
    (0, 'Rotwood Brown', 'AK Interactive', 'Wash'),
    (0, 'Obsidian Holt', 'AK Interactive', 'Wash'),
    (0, 'Black Night', 'AK Interactive', 'Wash'),
    (0, 'Pure Grime', 'AK Interactive', 'Wash'),
    (0, 'Sepia Filth', 'AK Interactive', 'Wash'),
    (0, 'Hazel Brown', 'AK Interactive', 'Wash'),
    (0, 'Blue Moon', 'AK Interactive', 'Wash'),
    (0, 'Carmine Dawn', 'AK Interactive', 'Wash'),
    (0, 'Invocation Purple', 'AK Interactive', 'Wash'),
    (0, 'Crimson Veil', 'AK Interactive', 'Wash'),
    (0, 'Putrid Green', 'AK Interactive', 'Wash'),
    (0, 'Green', 'AK Interactive', 'Wash'),
    (0, 'Verdigris', 'AK Interactive', 'Wash'),
    (0, 'Dark Grey', 'AK Interactive', 'Wash'),
    (0, 'Standard Rust', 'AK Interactive', 'Wash'),
    (0, 'Light Rust', 'AK Interactive', 'Wash'),
    (0, 'Dirtveil', 'AK Interactive', 'Wash'),
    (0, 'Woodgrain', 'AK Interactive', 'Wash'),
    (0, 'Light Grey Precision Panel Liner', 'AK Interactive', 'Wash'),
    (0, 'Black Precision Panel Liner', 'AK Interactive', 'Wash'),
    (0, 'Sepia Precision Panel Liner', 'AK Interactive', 'Wash'),
    (0, 'Decal Setter', 'AK Interactive', 'Technical'),
    (0, 'Decal Softener', 'AK Interactive', 'Technical'),
    (0, 'WWI GERMAN FOKKER GREY', 'AK Interactive', 'Paint'),
    (0, 'WWI GERMAN LIGHT GREEN', 'AK Interactive', 'Paint'),
    (0, 'WWI GERMAN MAUVE', 'AK Interactive', 'Paint'),
    (0, 'WWI GERMAN RED BROWN', 'AK Interactive', 'Paint'),
    (0, 'WWI GERMAN LIGHT BLUE', 'AK Interactive', 'Paint'),
    (0, 'WWI GERMAN LILAC', 'AK Interactive', 'Paint'),
    (0, 'WWI GERMAN GREY-GREEN PRIMER', 'AK Interactive', 'Primer'),
    (0, 'PC10 LATE', 'AK Interactive', 'Paint'),
    (0, 'PC12', 'AK Interactive', 'Paint'),
    (0, 'RLM 02 RLM-GRAU (1938)', 'AK Interactive', 'Paint'),
    (0, 'RLM 02 RLM-GRAU (1941)', 'AK Interactive', 'Paint'),
    (0, 'RLM 04', 'AK Interactive', 'Paint'),
    (0, 'RLM 61', 'AK Interactive', 'Paint'),
    (0, 'RLM 62', 'AK Interactive', 'Paint'),
    (0, 'RLM 63', 'AK Interactive', 'Paint'),
    (0, 'RLM 65 (1938)', 'AK Interactive', 'Paint'),
    (0, 'RLM 65 (1941)', 'AK Interactive', 'Paint'),
    (0, 'RLM 66 (1938)', 'AK Interactive', 'Paint'),
    (0, 'RLM 66 (1941)', 'AK Interactive', 'Paint'),
    (0, 'RLM 70', 'AK Interactive', 'Paint'),
    (0, 'RLM 71', 'AK Interactive', 'Paint'),
    (0, 'RLM 72', 'AK Interactive', 'Paint'),
    (0, 'RLM 73', 'AK Interactive', 'Paint'),
    (0, 'RLM 74', 'AK Interactive', 'Paint'),
    (0, 'RLM 75', 'AK Interactive', 'Paint'),
    (0, 'RLM 76 VERSION 1', 'AK Interactive', 'Paint'),
    (0, 'RLM 76 VERSION 2', 'AK Interactive', 'Paint'),
    (0, 'RLM 76 LATE WAR VARIATION', 'AK Interactive', 'Paint'),
    (0, 'RLM 78 (1941)', 'AK Interactive', 'Paint'),
    (0, 'RLM 78 (1942)', 'AK Interactive', 'Paint'),
    (0, 'RLM 79 (1941)', 'AK Interactive', 'Paint'),
    (0, 'RLM 79 (1942)', 'AK Interactive', 'Paint'),
    (0, 'RLM 80', 'AK Interactive', 'Paint'),
    (0, 'RLM 81 VERSION 1', 'AK Interactive', 'Paint'),
    (0, 'RLM 81 VERSION 2', 'AK Interactive', 'Paint'),
    (0, 'RLM 81 VERSION 3', 'AK Interactive', 'Paint'),
    (0, 'RLM 82', 'AK Interactive', 'Paint'),
    (0, 'RLM 83', 'AK Interactive', 'Paint'),
    (0, 'RAF DARK GREEN', 'AK Interactive', 'Paint'),
    (0, 'RAF DARK EARTH', 'AK Interactive', 'Paint'),
    (0, 'RAF OCEAN GREY', 'AK Interactive', 'Paint'),
    (0, 'RAF MEDIUM SEA GREY BS381C/637', 'AK Interactive', 'Paint'),
    (0, 'RAF SKY / FS 34424', 'AK Interactive', 'Paint'),
    (0, 'RAF AZURE BLUE', 'AK Interactive', 'Paint'),
    (0, 'RAF MIDDLE STONE', 'AK Interactive', 'Paint'),
    (0, 'RAF COCKPIT GREY-GREEN', 'AK Interactive', 'Paint'),
    (0, 'RAF SKY GREY', 'AK Interactive', 'Paint'),
    (0, 'RAF DARK SLATE GREY', 'AK Interactive', 'Paint'),
    (0, 'RAF EXTRA DARK SEA GREY BS381C/640', 'AK Interactive', 'Paint'),
    (0, 'RAF DARK SEA GREY BS381C/638', 'AK Interactive', 'Paint'),
    (0, 'RAF PRU BLUE BS381C/636', 'AK Interactive', 'Paint'),
    (0, 'RAF LIGHT AIRCRAFT GREY BS381C/627', 'AK Interactive', 'Paint'),
    (0, 'RAF CAMOUFLAGE (BARLEY) GREY BS381C/626', 'AK Interactive', 'Paint'),
    (0, 'RAF DARK CAMOUFLAGE GREY BS381C/629', 'AK Interactive', 'Paint'),
    (0, 'RAF CAMOUFLAGE BEIGE (HEMP) BS381C/389', 'AK Interactive', 'Paint'),
    (0, 'BRONZE GREEN', 'AK Interactive', 'Paint'),
    (0, 'ZINC CHROMATE YELLOW', 'AK Interactive', 'Paint'),
    (0, 'US INTERIOR YELLOW GREEN', 'AK Interactive', 'Paint'),
    (0, 'DARK OLIVE DRAB 41', 'AK Interactive', 'Paint'),
    (0, 'MEDIUM GREEN 42', 'AK Interactive', 'Paint'),
    (0, 'NEUTRAL GREY 43', 'AK Interactive', 'Paint'),
    (0, 'ANA 613 OLIVE DRAB', 'AK Interactive', 'Paint'),
    (0, 'DEEP SEA BLUE', 'AK Interactive', 'Paint'),
    (0, 'M-485 BLUE-GREY', 'AK Interactive', 'Paint'),
    (0, 'LIGHT GULL GREY FS 16440', 'AK Interactive', 'Paint'),
    (0, 'ADC GREY FS 16473', 'AK Interactive', 'Paint'),
    (0, 'INSIGNIA WHITE FS 17875', 'AK Interactive', 'Paint'),
    (0, 'SAND FS 33531', 'AK Interactive', 'Paint'),
    (0, 'RADOME TAN FS 33613', 'AK Interactive', 'Paint'),
    (0, 'USMC SAND FS 33711', 'AK Interactive', 'Paint'),
    (0, 'US ARMY HELO DRAB FS 34031', 'AK Interactive', 'Paint'),
    (0, 'DULL DARK GREEN FS 34092', 'AK Interactive', 'Paint'),
    (0, 'USMC GREEN FS 34095', 'AK Interactive', 'Paint'),
    (0, 'FIELD GREEN FS 34097', 'AK Interactive', 'Paint'),
    (0, 'GREEN FS 34258', 'AK Interactive', 'Paint'),
    (0, 'AGGRESSOR BLUE FS 35109', 'AK Interactive', 'Paint'),
    (0, 'BLUE FS 35190', 'AK Interactive', 'Paint'),
    (0, 'AIR SUPERIORITY BLUE FS 35450', 'AK Interactive', 'Paint'),
    (0, 'DUCK EGG BLUE FS 35622', 'AK Interactive', 'Paint'),
    (0, 'MEDIUM GUNSHIP GREY FS 36118', 'AK Interactive', 'Paint'),
    (0, 'HAVE GLASS GREY FS 36170', 'AK Interactive', 'Paint'),
    (0, 'F-15 DARK GREY (MOD EAGLE) FS 36176', 'AK Interactive', 'Paint'),
    (0, 'DARK GULL GREY FS 36231', 'AK Interactive', 'Paint'),
    (0, 'AGGRESSOR GREY FS 36251', 'AK Interactive', 'Paint'),
    (0, 'MEDIUM GREY FS 36270', 'AK Interactive', 'Paint'),
    (0, 'DARK GHOST GREY FS 36320', 'AK Interactive', 'Paint'),
    (0, 'LIGHT GHOST GREY FS 36375', 'AK Interactive', 'Paint'),
    (0, 'LIGHT GREY FS 36495', 'AK Interactive', 'Paint'),
    (0, 'CAMOUFLAGE GREY FS 36622', 'AK Interactive', 'Paint'),
    (0, 'IJN J3 HAI-IRO (GREY)', 'AK Interactive', 'Paint'),
    (0, 'IJN J3 SP (AMBER GREY)', 'AK Interactive', 'Paint'),
    (0, 'IJN D1 DEEP GREEN BLACK', 'AK Interactive', 'Paint'),
    (0, 'IJN D2 GREEN BLACK', 'AK Interactive', 'Paint'),
    (0, 'IJN Q1 ANTI-GLARE BLUE-BLACK', 'AK Interactive', 'Paint'),
    (0, 'IJN M3 (M) MITSUBISHI INTERIOR GREEN', 'AK Interactive', 'Paint'),
    (0, 'IJN M3 (N) NAKAJIMA INTERIOR GREEN', 'AK Interactive', 'Paint'),
    (0, 'IJN/IJA AOTAKE', 'AK Interactive', 'Paint'),
    (0, 'IJA #1 HAIRYOKUSHOKU (GREY-GREEN)', 'AK Interactive', 'Paint'),
    (0, 'IJA #3 HAIRANSHOKU (GREY INDIGO)', 'AK Interactive', 'Paint'),
    (0, 'IJA #7 OHRYUKO NANA GO SHOKU (OLIVE BROWN)', 'AK Interactive', 'Paint'),
    (0, 'IJA #21 MIDORI IRO (GREEN)', 'AK Interactive', 'Paint'),
    (0, 'IJA #27 AO MIDORI IRO (BLUE-GREEN)', 'AK Interactive', 'Paint'),
    (0, 'IJA #29 KI MIDORI IRO (YELLOW-GREEN)', 'AK Interactive', 'Paint'),
    (0, 'IJA #30 KAREKUSA IRO (DRY GRASS)', 'AK Interactive', 'Paint'),
    (0, 'IJA #31 CHA KASSHOKU (TEA COLOUR)', 'AK Interactive', 'Paint'),
    (0, 'GREY-BLUE 1920S-1930S', 'AK Interactive', 'Paint'),
    (0, 'AE-9/AII LIGHT GREY', 'AK Interactive', 'Paint'),
    (0, 'AII GREEN', 'AK Interactive', 'Paint'),
    (0, 'AII LIGHT BLUE', 'AK Interactive', 'Paint'),
    (0, 'A-14 INTERIOR STEEL GREY', 'AK Interactive', 'Paint'),
    (0, 'A-18F LIGHT GREY-BLUE', 'AK Interactive', 'Paint'),
    (0, 'A-19F GRASS GREEN', 'AK Interactive', 'Paint'),
    (0, 'A-21M LIGHT YELLOWISH BROWN', 'AK Interactive', 'Paint'),
    (0, 'AMT-4 (A-24M) GREEN', 'AK Interactive', 'Paint'),
    (0, 'AMT-7 LIGHT BLUE', 'AK Interactive', 'Paint'),
    (0, 'AMT-11 BLUE-GREY', 'AK Interactive', 'Paint'),
    (0, 'AMT-12 DARK GREY', 'AK Interactive', 'Paint'),
    (0, 'RADOME & WHEEL HUB GREEN', 'AK Interactive', 'Paint'),
    (0, "MIG-25/MIG-31 GREY", "AK Interactive", "Paint")
]


def toggle_check(event):
    rowid = treeview.identify_row(event.y)
    if not rowid:
        return
    tag = treeview.item(rowid, "tags")[0]
    if tag == "checked":
        new_tag = "unchecked"
        paint_owned = 0
    else:
        new_tag = "checked"
        paint_owned = 1
    
    # Update the tag in the Treeview
    treeview.item(rowid, tags=new_tag)
    
    # Get the paint name (or a unique identifier) from the row values
    values = treeview.item(rowid, "values")
    paint_name = values[0]
    
    # Update the database
    cursor.execute("UPDATE paints SET paint_owned = ? WHERE paint_name = ?", (paint_owned, paint_name))
    connection.commit()  # Save the change to the database

#create main window
root = tk.Tk()

#set window title
root.title("Paint Catalogue")

#set window size
root.geometry("800x600")

#load image
#Abaddon = Image.open("images/citadel-abaddon-black.jpg").resize((250, 188))
#Abaddon = ImageTk.PhotoImage(Abaddon)

im_checked = Image.open("images/checked.png")
im_checked = ImageTk.PhotoImage(im_checked)
im_unchecked = Image.open("images/unchecked.png")
im_unchecked = ImageTk.PhotoImage(im_unchecked)

#create a label
abaddon_label = tk.Label(root, background = '#231F20').pack(expand = True, fill = 'both')
#abaddon_label.image = Abaddon  # Keep reference

#treeview creation
treeview = ttk.Treeview(root, columns=("name", "brand", "paint_type"), show=("headings", "tree"))

treeview.tag_configure('checked', image=im_checked)
treeview.tag_configure('unchecked', image=im_unchecked)

treeview.heading("#0", text="Owned")
treeview.heading("#1", text="Name")
treeview.heading("#2", text="Brand")
treeview.heading("#3", text="Paint_Type")
treeview.pack(fill=tk.BOTH, expand=True, padx=10, pady=10)

treeview.bind('<Button 1>', toggle_check)

#define connection and cursor
connection = sqlite3.connect("store_paints.db")

#used to execute SQL commands
cursor = connection.cursor()

#create paints table
cursor.execute("CREATE TABLE IF NOT EXISTS paints (paint_owned INTEGER CHECK (paint_owned IN (0, 1)), paint_name TEXT, paint_brand TEXT, paint_type TEXT)")

#fill paints table with paint_list data
cursor.executemany("insert into paints values (?, ?, ?, ?)", paint_list)

#save database
connection.commit()

#retrieve data from paints table
cursor.execute("SELECT paint_owned, paint_name, paint_brand, paint_type FROM paints")
rows = cursor.fetchall()

for item in treeview.get_children():
    treeview.delete(item)

#print paints to treeview table
for row in rows:
    owned, name, brand, paint_type = row
    tag = "checked" if owned == 1 else "unchecked"
    treeview.insert(parent="", index="end", values=(name, brand, paint_type), tags=tag)

#create scrollbar
v_scrollbar = ttk.Scrollbar(treeview, orient=tk.VERTICAL, command=treeview.yview)
#link with treeview widget
treeview.configure(yscrollcommand=v_scrollbar.set)
#pack the scrollbar
v_scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

#print specific rows
#cursor.execute("select * from paints where paint_type=:t", {"t": "Wash"})

#start GUI event loop
root.mainloop()

#End GUI event loop when closed
connection.close()